name: sfkafka
networks:
  sfkafka_net:
    driver: bridge
services:
  sf-kafka-connect:
    build:
      context: .
      args:
        SCALA_VERSION: ${SCALA_VERSION}
        KAFKA_VERSION: ${KAFKA_VERSION}
    networks:
      - sfkafka_net
    ports:
      - "8083:8083"
      - "1099:1099"
    volumes:
      - ./connect_lib:/opt/extra-libs
      - ./connect_plugins:/opt/plugins
      - ./connect-distributed.properties:/docker/connect-distributed-mounted.properties
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: ${HOSTNAME:-connect}
      CONNECT_REST_ADVERTISED_PORT: 8083
      CONNECT_LISTENERS: 'http://0.0.0.0:8083'
      CONNECT_REST_PORT: 8083
    env_file: connect.env
